jobs:
  run:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Begin
        uses: actions/checkout@v2
      - name: Pull Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Tests
        run: ./verify/ci

name: Run

on:
  schedule:
    - cron: "40 1/3 * * *"
